

<section class="section section-xl section-shaped">
    <div class="container py-md">
        <div class="col-lg-12">
            <div class="bg-secondary shadow border-0">
                <div class="card-header bg-white pb-5">
                    <div class="text-muted text-center mb-3"><h4>Form Survey Kepuasan Masyarakat</h4></div>
                </div>
                <div class="card-body px-lg-5 py-lg-5">
                    <form action="https://skm.dpmptsp.jatengprov.go.id/form-data-skm" method="post">
                        <input type="hidden" name="_token" value="QPs74mAbZ6bZsupRASk8p0Y2yxdZQYWaj8SKQ0Ab">                                                        
                        <div class="form-group">
                            <div class="input-slider-container">
                                <h5 class="text-dark font-weight-bold">Bagaimana pendapat saudara tentang kesesuaian persyaratan pelayanan yang ditetapkan dengan yang diminta oleh petugas?</h5>
                                <span class="irs irs--big js-irs-0 irs-with-grid"><span class="irs"><span class="irs-line" tabindex="0"></span><span class="irs-min" style="visibility: visible;">Tidak Baik</span><span class="irs-max" style="visibility: hidden;">Sangat Baik</span><span class="irs-from" style="visibility: hidden;">0</span><span class="irs-to" style="visibility: hidden;">0</span><span class="irs-single" style="left: 83.9388%;">Sangat Baik</span></span><span class="irs-grid" style="width: 90.7975%; left: 4.50123%;"><span class="irs-grid-pol" style="left: 0%"></span><span class="irs-grid-text js-grid-text-0" style="left: 0%; margin-left: -7.31403%;">Tidak Baik</span><span class="irs-grid-pol small" style="left: 26.666666666666668%"></span><span class="irs-grid-pol small" style="left: 20%"></span><span class="irs-grid-pol small" style="left: 13.333333333333336%"></span><span class="irs-grid-pol small" style="left: 6.666666666666668%"></span><span class="irs-grid-pol" style="left: 33.333333333333336%"></span><span class="irs-grid-text js-grid-text-1" style="left: 33.3333%; visibility: visible; margin-left: -8.44037%;">Kurang Baik</span><span class="irs-grid-pol small" style="left: 60.00000000000001%"></span><span class="irs-grid-pol small" style="left: 53.333333333333336%"></span><span class="irs-grid-pol small" style="left: 46.66666666666667%"></span><span class="irs-grid-pol small" style="left: 40%"></span><span class="irs-grid-pol" style="left: 66.66666666666667%"></span><span class="irs-grid-text js-grid-text-2" style="left: 66.6667%; visibility: visible; margin-left: -3.60669%;">Baik</span><span class="irs-grid-pol small" style="left: 93.33333333333333%"></span><span class="irs-grid-pol small" style="left: 86.66666666666667%"></span><span class="irs-grid-pol small" style="left: 80%"></span><span class="irs-grid-pol small" style="left: 73.33333333333334%"></span><span class="irs-grid-pol" style="left: 100%"></span><span class="irs-grid-text js-grid-text-3" style="left: 100%; visibility: visible; margin-left: -8.36609%;">Sangat Baik</span></span><span class="irs-bar irs-bar--single" style="left: 0px; width: 95.3988%;"></span><span class="irs-shadow shadow-single" style="display: none;"></span><span class="irs-handle single" style="left: 90.7975%;"><i></i><i></i><i></i></span></span><input class="js-range-slider irs-hidden-input" name="p1" id="1" type="text" tabindex="-1" readonly="">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-slider-container">
                                <h5 class="text-dark font-weight-bold">Bagaimana pemahaman saudara tentang kemudahan prosedur pelayanan dan pengaduan di Dinas Perizinan?</h5>
                                <span class="irs irs--big js-irs-1 irs-with-grid"><span class="irs"><span class="irs-line" tabindex="0"></span><span class="irs-min" style="visibility: visible;">Tidak Baik</span><span class="irs-max" style="visibility: hidden;">Sangat Baik</span><span class="irs-from" style="visibility: hidden;">0</span><span class="irs-to" style="visibility: hidden;">0</span><span class="irs-single" style="left: 83.9388%;">Sangat Baik</span></span><span class="irs-grid" style="width: 90.7975%; left: 4.50123%;"><span class="irs-grid-pol" style="left: 0%"></span><span class="irs-grid-text js-grid-text-0" style="left: 0%; margin-left: -7.31403%;">Tidak Baik</span><span class="irs-grid-pol small" style="left: 26.666666666666668%"></span><span class="irs-grid-pol small" style="left: 20%"></span><span class="irs-grid-pol small" style="left: 13.333333333333336%"></span><span class="irs-grid-pol small" style="left: 6.666666666666668%"></span><span class="irs-grid-pol" style="left: 33.333333333333336%"></span><span class="irs-grid-text js-grid-text-1" style="left: 33.3333%; visibility: visible; margin-left: -8.44037%;">Kurang Baik</span><span class="irs-grid-pol small" style="left: 60.00000000000001%"></span><span class="irs-grid-pol small" style="left: 53.333333333333336%"></span><span class="irs-grid-pol small" style="left: 46.66666666666667%"></span><span class="irs-grid-pol small" style="left: 40%"></span><span class="irs-grid-pol" style="left: 66.66666666666667%"></span><span class="irs-grid-text js-grid-text-2" style="left: 66.6667%; visibility: visible; margin-left: -3.60669%;">Baik</span><span class="irs-grid-pol small" style="left: 93.33333333333333%"></span><span class="irs-grid-pol small" style="left: 86.66666666666667%"></span><span class="irs-grid-pol small" style="left: 80%"></span><span class="irs-grid-pol small" style="left: 73.33333333333334%"></span><span class="irs-grid-pol" style="left: 100%"></span><span class="irs-grid-text js-grid-text-3" style="left: 100%; visibility: visible; margin-left: -8.36609%;">Sangat Baik</span></span><span class="irs-bar irs-bar--single" style="left: 0px; width: 95.3988%;"></span><span class="irs-shadow shadow-single" style="display: none;"></span><span class="irs-handle single" style="left: 90.7975%;"><i></i><i></i><i></i></span></span><input class="js-range-slider irs-hidden-input" name="p2" id="2" type="text" tabindex="-1" readonly="">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-slider-container">
                                <h5 class="text-dark font-weight-bold">Bagaimana pendapat saudara tentang jangka waktu penyelesaian pelayanan?</h5>
                                <span class="irs irs--big js-irs-2 irs-with-grid"><span class="irs"><span class="irs-line" tabindex="0"></span><span class="irs-min" style="visibility: visible;">Tidak Baik</span><span class="irs-max" style="visibility: hidden;">Sangat Baik</span><span class="irs-from" style="visibility: hidden;">0</span><span class="irs-to" style="visibility: hidden;">0</span><span class="irs-single" style="left: 83.9388%;">Sangat Baik</span></span><span class="irs-grid" style="width: 90.7975%; left: 4.50123%;"><span class="irs-grid-pol" style="left: 0%"></span><span class="irs-grid-text js-grid-text-0" style="left: 0%; margin-left: -7.31403%;">Tidak Baik</span><span class="irs-grid-pol small" style="left: 26.666666666666668%"></span><span class="irs-grid-pol small" style="left: 20%"></span><span class="irs-grid-pol small" style="left: 13.333333333333336%"></span><span class="irs-grid-pol small" style="left: 6.666666666666668%"></span><span class="irs-grid-pol" style="left: 33.333333333333336%"></span><span class="irs-grid-text js-grid-text-1" style="left: 33.3333%; visibility: visible; margin-left: -8.44037%;">Kurang Baik</span><span class="irs-grid-pol small" style="left: 60.00000000000001%"></span><span class="irs-grid-pol small" style="left: 53.333333333333336%"></span><span class="irs-grid-pol small" style="left: 46.66666666666667%"></span><span class="irs-grid-pol small" style="left: 40%"></span><span class="irs-grid-pol" style="left: 66.66666666666667%"></span><span class="irs-grid-text js-grid-text-2" style="left: 66.6667%; visibility: visible; margin-left: -3.60669%;">Baik</span><span class="irs-grid-pol small" style="left: 93.33333333333333%"></span><span class="irs-grid-pol small" style="left: 86.66666666666667%"></span><span class="irs-grid-pol small" style="left: 80%"></span><span class="irs-grid-pol small" style="left: 73.33333333333334%"></span><span class="irs-grid-pol" style="left: 100%"></span><span class="irs-grid-text js-grid-text-3" style="left: 100%; visibility: visible; margin-left: -8.36609%;">Sangat Baik</span></span><span class="irs-bar irs-bar--single" style="left: 0px; width: 95.3988%;"></span><span class="irs-shadow shadow-single" style="display: none;"></span><span class="irs-handle single" style="left: 90.7975%;"><i></i><i></i><i></i></span></span><input class="js-range-slider irs-hidden-input" name="p3" id="3" type="text" tabindex="-1" readonly="">
                            </div>
                        </div>
                                                    <div class="form-group">
                            <div class="input-slider-container">
                                <h5 class="text-dark font-weight-bold">Bagaimana pendapat saudara tentang kesesuaian antara biaya/tarif yang dibayarkan dengan biaya yang telah ditetapkan?</h5>
                                <span class="irs irs--big js-irs-3 irs-with-grid"><span class="irs"><span class="irs-line" tabindex="0"></span><span class="irs-min" style="visibility: visible;">Tidak Baik</span><span class="irs-max" style="visibility: hidden;">Sangat Baik</span><span class="irs-from" style="visibility: hidden;">0</span><span class="irs-to" style="visibility: hidden;">0</span><span class="irs-single" style="left: 83.9388%;">Sangat Baik</span></span><span class="irs-grid" style="width: 90.7975%; left: 4.50123%;"><span class="irs-grid-pol" style="left: 0%"></span><span class="irs-grid-text js-grid-text-0" style="left: 0%; margin-left: -7.31403%;">Tidak Baik</span><span class="irs-grid-pol small" style="left: 26.666666666666668%"></span><span class="irs-grid-pol small" style="left: 20%"></span><span class="irs-grid-pol small" style="left: 13.333333333333336%"></span><span class="irs-grid-pol small" style="left: 6.666666666666668%"></span><span class="irs-grid-pol" style="left: 33.333333333333336%"></span><span class="irs-grid-text js-grid-text-1" style="left: 33.3333%; visibility: visible; margin-left: -8.44037%;">Kurang Baik</span><span class="irs-grid-pol small" style="left: 60.00000000000001%"></span><span class="irs-grid-pol small" style="left: 53.333333333333336%"></span><span class="irs-grid-pol small" style="left: 46.66666666666667%"></span><span class="irs-grid-pol small" style="left: 40%"></span><span class="irs-grid-pol" style="left: 66.66666666666667%"></span><span class="irs-grid-text js-grid-text-2" style="left: 66.6667%; visibility: visible; margin-left: -3.60669%;">Baik</span><span class="irs-grid-pol small" style="left: 93.33333333333333%"></span><span class="irs-grid-pol small" style="left: 86.66666666666667%"></span><span class="irs-grid-pol small" style="left: 80%"></span><span class="irs-grid-pol small" style="left: 73.33333333333334%"></span><span class="irs-grid-pol" style="left: 100%"></span><span class="irs-grid-text js-grid-text-3" style="left: 100%; visibility: visible; margin-left: -8.36609%;">Sangat Baik</span></span><span class="irs-bar irs-bar--single" style="left: 0px; width: 95.3988%;"></span><span class="irs-shadow shadow-single" style="display: none;"></span><span class="irs-handle single" style="left: 90.7975%;"><i></i><i></i><i></i></span></span><input class="js-range-slider irs-hidden-input" name="p4" id="4" type="text" tabindex="-1" readonly="">
                            </div>
                        </div>
                                                    <div class="form-group">
                            <div class="input-slider-container">
                                <h5 class="text-dark font-weight-bold">Bagaimana pendapat saudara tentang kesesuaian hasil pelayanan dengan ketentuan yang telah di tetapkan?</h5>
                                <span class="irs irs--big js-irs-4 irs-with-grid"><span class="irs"><span class="irs-line" tabindex="0"></span><span class="irs-min" style="visibility: visible;">Tidak Baik</span><span class="irs-max" style="visibility: hidden;">Sangat Baik</span><span class="irs-from" style="visibility: hidden;">0</span><span class="irs-to" style="visibility: hidden;">0</span><span class="irs-single" style="left: 83.9388%;">Sangat Baik</span></span><span class="irs-grid" style="width: 90.7975%; left: 4.50123%;"><span class="irs-grid-pol" style="left: 0%"></span><span class="irs-grid-text js-grid-text-0" style="left: 0%; margin-left: -7.31403%;">Tidak Baik</span><span class="irs-grid-pol small" style="left: 26.666666666666668%"></span><span class="irs-grid-pol small" style="left: 20%"></span><span class="irs-grid-pol small" style="left: 13.333333333333336%"></span><span class="irs-grid-pol small" style="left: 6.666666666666668%"></span><span class="irs-grid-pol" style="left: 33.333333333333336%"></span><span class="irs-grid-text js-grid-text-1" style="left: 33.3333%; visibility: visible; margin-left: -8.44037%;">Kurang Baik</span><span class="irs-grid-pol small" style="left: 60.00000000000001%"></span><span class="irs-grid-pol small" style="left: 53.333333333333336%"></span><span class="irs-grid-pol small" style="left: 46.66666666666667%"></span><span class="irs-grid-pol small" style="left: 40%"></span><span class="irs-grid-pol" style="left: 66.66666666666667%"></span><span class="irs-grid-text js-grid-text-2" style="left: 66.6667%; visibility: visible; margin-left: -3.60669%;">Baik</span><span class="irs-grid-pol small" style="left: 93.33333333333333%"></span><span class="irs-grid-pol small" style="left: 86.66666666666667%"></span><span class="irs-grid-pol small" style="left: 80%"></span><span class="irs-grid-pol small" style="left: 73.33333333333334%"></span><span class="irs-grid-pol" style="left: 100%"></span><span class="irs-grid-text js-grid-text-3" style="left: 100%; visibility: visible; margin-left: -8.36609%;">Sangat Baik</span></span><span class="irs-bar irs-bar--single" style="left: 0px; width: 95.3988%;"></span><span class="irs-shadow shadow-single" style="display: none;"></span><span class="irs-handle single" style="left: 90.7975%;"><i></i><i></i><i></i></span></span><input class="js-range-slider irs-hidden-input" name="p5" id="5" type="text" tabindex="-1" readonly="">
                            </div>
                        </div>
                                                    <div class="form-group">
                            <div class="input-slider-container">
                                <h5 class="text-dark font-weight-bold">Bagaimana pendapat saudara tentang kemampuan yang dimilki petugas dalam memberikan pelayanan baik dari aspek pengetahuan, keahlian, ketrampilan dan pengalaman?</h5>
                                <span class="irs irs--big js-irs-5 irs-with-grid"><span class="irs"><span class="irs-line" tabindex="0"></span><span class="irs-min" style="visibility: visible;">Tidak Baik</span><span class="irs-max" style="visibility: hidden;">Sangat Baik</span><span class="irs-from" style="visibility: hidden;">0</span><span class="irs-to" style="visibility: hidden;">0</span><span class="irs-single" style="left: 83.9388%;">Sangat Baik</span></span><span class="irs-grid" style="width: 90.7975%; left: 4.50123%;"><span class="irs-grid-pol" style="left: 0%"></span><span class="irs-grid-text js-grid-text-0" style="left: 0%; margin-left: -7.31403%;">Tidak Baik</span><span class="irs-grid-pol small" style="left: 26.666666666666668%"></span><span class="irs-grid-pol small" style="left: 20%"></span><span class="irs-grid-pol small" style="left: 13.333333333333336%"></span><span class="irs-grid-pol small" style="left: 6.666666666666668%"></span><span class="irs-grid-pol" style="left: 33.333333333333336%"></span><span class="irs-grid-text js-grid-text-1" style="left: 33.3333%; visibility: visible; margin-left: -8.44037%;">Kurang Baik</span><span class="irs-grid-pol small" style="left: 60.00000000000001%"></span><span class="irs-grid-pol small" style="left: 53.333333333333336%"></span><span class="irs-grid-pol small" style="left: 46.66666666666667%"></span><span class="irs-grid-pol small" style="left: 40%"></span><span class="irs-grid-pol" style="left: 66.66666666666667%"></span><span class="irs-grid-text js-grid-text-2" style="left: 66.6667%; visibility: visible; margin-left: -3.60669%;">Baik</span><span class="irs-grid-pol small" style="left: 93.33333333333333%"></span><span class="irs-grid-pol small" style="left: 86.66666666666667%"></span><span class="irs-grid-pol small" style="left: 80%"></span><span class="irs-grid-pol small" style="left: 73.33333333333334%"></span><span class="irs-grid-pol" style="left: 100%"></span><span class="irs-grid-text js-grid-text-3" style="left: 100%; visibility: visible; margin-left: -8.36609%;">Sangat Baik</span></span><span class="irs-bar irs-bar--single" style="left: 0px; width: 95.3988%;"></span><span class="irs-shadow shadow-single" style="display: none;"></span><span class="irs-handle single" style="left: 90.7975%;"><i></i><i></i><i></i></span></span><input class="js-range-slider irs-hidden-input" name="p6" id="6" type="text" tabindex="-1" readonly="">
                            </div>
                        </div>
                                                    <div class="form-group">
                            <div class="input-slider-container">
                                <h5 class="text-dark font-weight-bold">Bagaimana pendapat saudara tentang perilaku petugas dalam memberikan pelayanan?</h5>
                                <span class="irs irs--big js-irs-6 irs-with-grid"><span class="irs"><span class="irs-line" tabindex="0"></span><span class="irs-min" style="visibility: visible;">Tidak Baik</span><span class="irs-max" style="visibility: hidden;">Sangat Baik</span><span class="irs-from" style="visibility: hidden;">0</span><span class="irs-to" style="visibility: hidden;">0</span><span class="irs-single" style="left: 83.9388%;">Sangat Baik</span></span><span class="irs-grid" style="width: 90.7975%; left: 4.50123%;"><span class="irs-grid-pol" style="left: 0%"></span><span class="irs-grid-text js-grid-text-0" style="left: 0%; margin-left: -7.31403%;">Tidak Baik</span><span class="irs-grid-pol small" style="left: 26.666666666666668%"></span><span class="irs-grid-pol small" style="left: 20%"></span><span class="irs-grid-pol small" style="left: 13.333333333333336%"></span><span class="irs-grid-pol small" style="left: 6.666666666666668%"></span><span class="irs-grid-pol" style="left: 33.333333333333336%"></span><span class="irs-grid-text js-grid-text-1" style="left: 33.3333%; visibility: visible; margin-left: -8.44037%;">Kurang Baik</span><span class="irs-grid-pol small" style="left: 60.00000000000001%"></span><span class="irs-grid-pol small" style="left: 53.333333333333336%"></span><span class="irs-grid-pol small" style="left: 46.66666666666667%"></span><span class="irs-grid-pol small" style="left: 40%"></span><span class="irs-grid-pol" style="left: 66.66666666666667%"></span><span class="irs-grid-text js-grid-text-2" style="left: 66.6667%; visibility: visible; margin-left: -3.60669%;">Baik</span><span class="irs-grid-pol small" style="left: 93.33333333333333%"></span><span class="irs-grid-pol small" style="left: 86.66666666666667%"></span><span class="irs-grid-pol small" style="left: 80%"></span><span class="irs-grid-pol small" style="left: 73.33333333333334%"></span><span class="irs-grid-pol" style="left: 100%"></span><span class="irs-grid-text js-grid-text-3" style="left: 100%; visibility: visible; margin-left: -8.36609%;">Sangat Baik</span></span><span class="irs-bar irs-bar--single" style="left: 0px; width: 95.3988%;"></span><span class="irs-shadow shadow-single" style="display: none;"></span><span class="irs-handle single" style="left: 90.7975%;"><i></i><i></i><i></i></span></span><input class="js-range-slider irs-hidden-input" name="p7" id="7" type="text" tabindex="-1" readonly="">
                            </div>
                        </div>
                                                    <div class="form-group">
                            <div class="input-slider-container">
                                <h5 class="text-dark font-weight-bold">Bagaimana pendapat saudara tentang sarana prasarana pelayanan?</h5>
                                <span class="irs irs--big js-irs-7 irs-with-grid"><span class="irs"><span class="irs-line" tabindex="0"></span><span class="irs-min" style="visibility: visible;">Tidak Baik</span><span class="irs-max" style="visibility: hidden;">Sangat Baik</span><span class="irs-from" style="visibility: hidden;">0</span><span class="irs-to" style="visibility: hidden;">0</span><span class="irs-single" style="left: 83.9388%;">Sangat Baik</span></span><span class="irs-grid" style="width: 90.7975%; left: 4.50123%;"><span class="irs-grid-pol" style="left: 0%"></span><span class="irs-grid-text js-grid-text-0" style="left: 0%; margin-left: -7.31403%;">Tidak Baik</span><span class="irs-grid-pol small" style="left: 26.666666666666668%"></span><span class="irs-grid-pol small" style="left: 20%"></span><span class="irs-grid-pol small" style="left: 13.333333333333336%"></span><span class="irs-grid-pol small" style="left: 6.666666666666668%"></span><span class="irs-grid-pol" style="left: 33.333333333333336%"></span><span class="irs-grid-text js-grid-text-1" style="left: 33.3333%; visibility: visible; margin-left: -8.44037%;">Kurang Baik</span><span class="irs-grid-pol small" style="left: 60.00000000000001%"></span><span class="irs-grid-pol small" style="left: 53.333333333333336%"></span><span class="irs-grid-pol small" style="left: 46.66666666666667%"></span><span class="irs-grid-pol small" style="left: 40%"></span><span class="irs-grid-pol" style="left: 66.66666666666667%"></span><span class="irs-grid-text js-grid-text-2" style="left: 66.6667%; visibility: visible; margin-left: -3.60669%;">Baik</span><span class="irs-grid-pol small" style="left: 93.33333333333333%"></span><span class="irs-grid-pol small" style="left: 86.66666666666667%"></span><span class="irs-grid-pol small" style="left: 80%"></span><span class="irs-grid-pol small" style="left: 73.33333333333334%"></span><span class="irs-grid-pol" style="left: 100%"></span><span class="irs-grid-text js-grid-text-3" style="left: 100%; visibility: visible; margin-left: -8.36609%;">Sangat Baik</span></span><span class="irs-bar irs-bar--single" style="left: 0px; width: 95.3988%;"></span><span class="irs-shadow shadow-single" style="display: none;"></span><span class="irs-handle single" style="left: 90.7975%;"><i></i><i></i><i></i></span></span><input class="js-range-slider irs-hidden-input" name="p8" id="8" type="text" tabindex="-1" readonly="">
                            </div>
                        </div>
                                                    <div class="form-group">
                            <div class="input-slider-container">
                                <h5 class="text-dark font-weight-bold">Bagaimana pendapat saudara tentang mekanisme dan respon penanganan pengaduan dalam penyelenggara pelayanan publik?</h5>
                                <span class="irs irs--big js-irs-8 irs-with-grid"><span class="irs"><span class="irs-line" tabindex="0"></span><span class="irs-min" style="visibility: visible;">Tidak Baik</span><span class="irs-max" style="visibility: hidden;">Sangat Baik</span><span class="irs-from" style="visibility: hidden;">0</span><span class="irs-to" style="visibility: hidden;">0</span><span class="irs-single" style="left: 83.9388%;">Sangat Baik</span></span><span class="irs-grid" style="width: 90.7975%; left: 4.50123%;"><span class="irs-grid-pol" style="left: 0%"></span><span class="irs-grid-text js-grid-text-0" style="left: 0%; margin-left: -7.31403%;">Tidak Baik</span><span class="irs-grid-pol small" style="left: 26.666666666666668%"></span><span class="irs-grid-pol small" style="left: 20%"></span><span class="irs-grid-pol small" style="left: 13.333333333333336%"></span><span class="irs-grid-pol small" style="left: 6.666666666666668%"></span><span class="irs-grid-pol" style="left: 33.333333333333336%"></span><span class="irs-grid-text js-grid-text-1" style="left: 33.3333%; visibility: visible; margin-left: -8.44037%;">Kurang Baik</span><span class="irs-grid-pol small" style="left: 60.00000000000001%"></span><span class="irs-grid-pol small" style="left: 53.333333333333336%"></span><span class="irs-grid-pol small" style="left: 46.66666666666667%"></span><span class="irs-grid-pol small" style="left: 40%"></span><span class="irs-grid-pol" style="left: 66.66666666666667%"></span><span class="irs-grid-text js-grid-text-2" style="left: 66.6667%; visibility: visible; margin-left: -3.60669%;">Baik</span><span class="irs-grid-pol small" style="left: 93.33333333333333%"></span><span class="irs-grid-pol small" style="left: 86.66666666666667%"></span><span class="irs-grid-pol small" style="left: 80%"></span><span class="irs-grid-pol small" style="left: 73.33333333333334%"></span><span class="irs-grid-pol" style="left: 100%"></span><span class="irs-grid-text js-grid-text-3" style="left: 100%; visibility: visible; margin-left: -8.36609%;">Sangat Baik</span></span><span class="irs-bar irs-bar--single" style="left: 0px; width: 95.3988%;"></span><span class="irs-shadow shadow-single" style="display: none;"></span><span class="irs-handle single" style="left: 90.7975%;"><i></i><i></i><i></i></span></span><input class="js-range-slider irs-hidden-input" name="p9" id="9" type="text" tabindex="-1" readonly="">
                            </div>
                        </div>
                                                    <div class="text-center">
                            <button type="submit" class="btn btn-primary btn-lg btn-block mt-4">Simpan !</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="container py-md mt-2 rounded">
            <div class="col-lg-12">
                <div class="bg-red-400 shadow border-0 rounded">
                    <div class="p-5 flex font-sans">
                        <div class="flex-none w-48 relative">
                        <img src="/classic-utility-jacket.jpg" alt="" class="absolute inset-0 w-full h-full object-cover" loading="lazy" />
                        </div>
                        <form class="flex-auto p-6">
                        <div class="flex flex-wrap">
                            <h1 class="flex-auto text-lg font-semibold text-slate-900">
                            Classic Utility Jacket
                            </h1>
                            <div class="text-lg font-semibold text-slate-500">
                            $110.00
                            </div>
                            <div class="w-full flex-none text-sm font-medium text-slate-700 mt-2">
                            In stock
                            </div>
                        </div>
                        <div class="flex items-baseline mt-4 mb-6 pb-6 border-b border-slate-200">
                            <div class="space-x-2 flex text-sm">
                            <label>
                                <input class="sr-only peer" name="size" type="radio" value="xs" checked />
                                <div class="w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white">
                                XS
                                </div>
                            </label>
                            <label>
                                <input class="sr-only peer" name="size" type="radio" value="s" />
                                <div class="w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white">
                                S
                                </div>
                            </label>
                            <label>
                                <input class="sr-only peer" name="size" type="radio" value="m" />
                                <div class="w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white">
                                M
                                </div>
                            </label>
                            <label>
                                <input class="sr-only peer" name="size" type="radio" value="l" />
                                <div class="w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white">
                                L
                                </div>
                            </label>
                            <label>
                                <input class="sr-only peer" name="size" type="radio" value="xl" />
                                <div class="w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white">
                                XL
                                </div>
                            </label>
                            </div>
                        </div>
                        <div class="flex space-x-4 mb-6 text-sm font-medium">
                            <div class="flex-auto flex space-x-4">
                            <button class="h-10 px-6 font-semibold rounded-md bg-black text-white" type="submit">
                                Buy now
                            </button>
                            <button class="h-10 px-6 font-semibold rounded-md border border-slate-200 text-slate-900" type="button">
                                Add to bag
                            </button>
                            </div>
                            <button class="flex-none flex items-center justify-center w-9 h-9 rounded-md text-slate-300 border border-slate-200" type="button" aria-label="Like">
                            <svg width="20" height="20" fill="currentColor" aria-hidden="true">
                                <path fill-rule="evenodd" clip-rule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" />
                            </svg>
                            </button>
                        </div>
                        <p class="text-sm text-slate-700">
                            Free shipping on all continental US orders.
                        </p>
                        </form>
                    </div>
                </div>
            </div>
    </div>
</section>